import { Category, Product, Founder } from "./types";

export const categories: Category[] = [
  { id: "dairy", name: "Dairy Products", icon: "🧀", description: "Premium dairy exports including cheese, butter, and milk powder", productCount: 12 },
  { id: "electronics", name: "Electronics", icon: "📱", description: "Cutting-edge electronic components and consumer devices", productCount: 18 },
  { id: "garments", name: "Readymade Garments", icon: "👔", description: "High-quality fashion and textile garments", productCount: 24 },
  { id: "cereals", name: "Cereals", icon: "🌾", description: "Organic and conventional grains and cereals", productCount: 15 },
  { id: "pharma", name: "Pharmaceuticals", icon: "💊", description: "WHO-certified pharmaceutical products", productCount: 20 },
  { id: "chemicals", name: "Organic Chemicals", icon: "⚗️", description: "Industrial and laboratory-grade organic chemicals", productCount: 10 },
  { id: "petroleum", name: "Petroleum Products", icon: "🛢️", description: "Refined petroleum and petrochemical products", productCount: 8 },
  { id: "textiles", name: "Textile Products", icon: "🧵", description: "Raw and processed textile materials", productCount: 22 },
  { id: "mechanical", name: "Mechanical Equipment", icon: "⚙️", description: "Industrial machinery and mechanical components", productCount: 14 },
  { id: "jewellery", name: "Jewellery", icon: "💎", description: "Exquisite gold, silver, and gemstone jewellery", productCount: 16 },
];

export const products: Product[] = [
  {
    id: "1",
    name: "Premium Basmati Rice",
    description: "Extra-long grain aged basmati rice, known for its exceptional aroma and fluffy texture. Sourced from the finest paddy fields of North India.",
    category: "Cereals",
    categoryId: "cereals",
    imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1536304929831-ee1ca9d44906?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1551462147-ff29053bfc14?w=800&h=600&fit=crop",
    ],
    moq: 500,
    moqUnit: "kg",
    origin: "India",
    packaging: "Export-grade PP bags, 25kg / 50kg",
    specifications: { "Grain Length": "8.3mm+", "Moisture": "≤12%", "Broken": "≤1%", "Aging": "2+ years", "Certification": "ISO 22000, FSSAI" },
    featured: true,
    tagline: "The Gold Standard in Rice",
  },
  {
    id: "2",
    name: "Organic Turmeric Powder",
    description: "High-curcumin organic turmeric powder, processed under strict quality controls. A cornerstone of Indian spice exports.",
    category: "Cereals",
    categoryId: "cereals",
    imageUrl: "https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=600&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&h=600&fit=crop",
    ],
    moq: 200,
    moqUnit: "kg",
    origin: "India",
    packaging: "Food-grade pouches, 1kg / 5kg / 25kg",
    specifications: { "Curcumin Content": "≥3%", "Moisture": "≤10%", "Type": "Alleppey/Erode", "Certification": "USDA Organic, FSSAI" },
    featured: true,
    tagline: "Nature's Golden Healer",
  },
  {
    id: "3",
    name: "Cotton T-Shirts Collection",
    description: "Premium 100% combed cotton t-shirts available in various styles and colors. Manufactured with precision stitching and superior fabric quality.",
    category: "Readymade Garments",
    categoryId: "garments",
    imageUrl: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1562157873-818bc0726f68?w=800&h=600&fit=crop",
    ],
    moq: 1000,
    moqUnit: "pieces",
    origin: "India",
    packaging: "Individual polybag, master carton",
    specifications: { "Fabric": "100% Combed Cotton", "GSM": "160-180", "Sizes": "S-3XL", "Colors": "20+ options", "Print": "Screen / DTG available" },
    featured: true,
    tagline: "Comfort Meets Quality",
  },
  {
    id: "4",
    name: "LED Panel Lights",
    description: "Energy-efficient LED panel lights suitable for commercial and residential use. High lumen output with minimal power consumption.",
    category: "Electronics",
    categoryId: "electronics",
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&h=600&fit=crop",
    ],
    moq: 500,
    moqUnit: "units",
    origin: "India",
    packaging: "Foam insert, corrugated box",
    specifications: { "Wattage": "18W / 24W / 36W", "Lumens": "1800-3600 lm", "Color Temp": "3000K-6500K", "Lifespan": "50,000 hours", "Certification": "BIS, CE" },
    featured: true,
    tagline: "Illuminating the Future",
  },
  {
    id: "5",
    name: "Ghee (Clarified Butter)",
    description: "Traditional pure cow ghee made from fresh cream using the bilona method. Rich aroma and golden color, perfect for cooking and rituals.",
    category: "Dairy Products",
    categoryId: "dairy",
    imageUrl: "https://images.unsplash.com/photo-1631452180539-96aca7d48617?w=600&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1631452180539-96aca7d48617?w=800&h=600&fit=crop",
    ],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Tin containers 1L / 5L / 15L",
    specifications: { "Fat Content": "≥99.5%", "Moisture": "≤0.5%", "Method": "Traditional Bilona", "Shelf Life": "12 months", "Certification": "FSSAI, Agmark" },
    featured: false,
    tagline: "Liquid Gold of India",
  },
  {
    id: "6",
    name: "Gold Necklace Set",
    description: "Intricately designed 22K gold necklace set featuring traditional Indian craftsmanship with modern aesthetics.",
    category: "Jewellery",
    categoryId: "jewellery",
    imageUrl: "https://images.unsplash.com/photo-1515562141589-67f0d0f6d51c?w=600&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1515562141589-67f0d0f6d51c?w=800&h=600&fit=crop",
    ],
    moq: 10,
    moqUnit: "sets",
    origin: "India",
    packaging: "Velvet box, tamper-proof seal",
    specifications: { "Purity": "22K (916)", "Weight Range": "20-50g", "Style": "Traditional & Contemporary", "Hallmarking": "BIS Hallmarked", "Certification": "BIS 916" },
    featured: true,
    tagline: "Art Meets Elegance",
  },
  {
    id: "7",
    name: "Paracetamol Tablets IP",
    description: "WHO-prequalified paracetamol tablets for fever and pain relief. Manufactured in GMP-certified facilities.",
    category: "Pharmaceuticals",
    categoryId: "pharma",
    imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&h=600&fit=crop",
    ],
    moq: 10000,
    moqUnit: "strips",
    origin: "India",
    packaging: "Blister pack, carton",
    specifications: { "Strength": "500mg / 650mg", "Pack Size": "10 tablets/strip", "Standards": "IP/BP/USP", "Shelf Life": "36 months", "Certification": "WHO GMP, FDA" },
    featured: false,
    tagline: "Healthcare Without Borders",
  },
  {
    id: "8",
    name: "Silk Fabric Rolls",
    description: "Premium Mulberry silk fabric rolls in various weaves and colors, ideal for fashion designers and textile houses worldwide.",
    category: "Textile Products",
    categoryId: "textiles",
    imageUrl: "https://images.unsplash.com/photo-1558171813-80f7b752d93d?w=600&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1558171813-80f7b752d93d?w=800&h=600&fit=crop",
    ],
    moq: 100,
    moqUnit: "meters",
    origin: "India",
    packaging: "Roll packing, carton box",
    specifications: { "Type": "Mulberry Silk", "Width": "44-45 inches", "Weight": "60-120 GSM", "Weave": "Plain / Satin / Twill", "Certification": "Silk Mark" },
    featured: true,
    tagline: "The Fabric of Royalty",
  },
  {
    id: "9",
    name: "CNC Machining Parts",
    description: "Precision CNC machined components in aluminum, steel, and brass. Custom manufacturing to specification with tight tolerances.",
    category: "Mechanical Equipment",
    categoryId: "mechanical",
    imageUrl: "https://images.unsplash.com/photo-1565043589221-1a6fd9ae45c7?w=600&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1565043589221-1a6fd9ae45c7?w=800&h=600&fit=crop",
    ],
    moq: 100,
    moqUnit: "pieces",
    origin: "India",
    packaging: "Anti-corrosion wrap, wooden crate",
    specifications: { "Materials": "AL 6061, SS 304/316, Brass", "Tolerance": "±0.01mm", "Finish": "Anodized / Polished / Powder Coat", "Lead Time": "15-20 days", "Certification": "ISO 9001:2015" },
    featured: false,
    tagline: "Precision Engineered",
  },
  {
    id: "10",
    name: "Base Oil SN-150",
    description: "High-quality Group I base oil suitable for industrial lubricant manufacturing. Consistent viscosity index and low sulfur content.",
    category: "Petroleum Products",
    categoryId: "petroleum",
    imageUrl: "https://images.unsplash.com/photo-1518709766631-a6a7f45921c3?w=600&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1518709766631-a6a7f45921c3?w=800&h=600&fit=crop",
    ],
    moq: 20,
    moqUnit: "MT",
    origin: "India",
    packaging: "Flexi-bags / ISO Tanks",
    specifications: { "Grade": "SN-150", "Viscosity": "150 cSt @ 40°C", "Sulfur": "≤0.3%", "Flash Point": "≥200°C", "Certification": "ISO 8217" },
    featured: false,
    tagline: "Industrial Grade Excellence",
  },
  {
    id: "11",
    name: "Citric Acid Monohydrate",
    description: "Food-grade citric acid monohydrate for use in beverages, food processing, and pharmaceutical applications.",
    category: "Organic Chemicals",
    categoryId: "chemicals",
    imageUrl: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=600&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800&h=600&fit=crop",
    ],
    moq: 500,
    moqUnit: "kg",
    origin: "India",
    packaging: "HDPE bags, 25kg",
    specifications: { "Purity": "≥99.5%", "Grade": "Food / Pharma", "Moisture": "≤8%", "Form": "Crystalline Powder", "Certification": "FSSAI, ISO" },
    featured: false,
    tagline: "Pure Chemistry, Pure Quality",
  },
  {
    id: "12",
    name: "Skimmed Milk Powder",
    description: "Premium spray-dried skimmed milk powder with excellent solubility. Ideal for dairy reconstitution and food manufacturing.",
    category: "Dairy Products",
    categoryId: "dairy",
    imageUrl: "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=600&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=800&h=600&fit=crop",
    ],
    moq: 1000,
    moqUnit: "kg",
    origin: "India",
    packaging: "Multi-wall kraft bags, 25kg",
    specifications: { "Protein": "≥34%", "Fat": "≤1.5%", "Moisture": "≤4%", "Solubility": "≥98%", "Certification": "FSSAI, EIA" },
    featured: false,
    tagline: "Nutrition Beyond Borders",
  },
];

export const founders: Founder[] = [
  {
    name: "Jayesh Avaiya",
    title: "Founder",
    phone: "+91 99253 53952",
    email: "[EMAIL_ADDRESS]",
    image: "/founders/jayesh.jpg",
  },
  {
    name: "Dipak Nakrani",
    title: "Founder",
    phone: "+91 97146 91751",
    email: "[EMAIL_ADDRESS]",
    image: "/founders/dipak.jpg",
  },
  {
    name: "Kalpesh Sabhani",
    title: "Founder",
    phone: "+91 99097 88944",
    email: "[EMAIL_ADDRESS]",
    image: "/founders/kalpesh.jpg",
  },
];

export const companyInfo = {
  name: "OM Export",
  tagline: "Global Trade & Export Services",
  email: "omexport291@gmail.com",
  description: "OM Export is a premier global trade and export company based in India, specializing in connecting international buyers with high-quality Indian products across diverse categories. With a commitment to excellence and reliability, we serve importers, distributors, and wholesalers in over 50 countries worldwide.",
  countriesServed: 50,
  totalProducts: 200,
  happyClients: 1000,
  yearsExperience: 10,
};
