import { Category, Product, Founder } from "./types";

export const categories: Category[] = [
  {
    id: "dairy",
    name: "Dairy Products",
    icon: "🧀",
    description:
      "Premium dairy exports including cheese, butter, and milk powder",
    productCount: 12,
  },
  {
    id: "electronics",
    name: "Electronics",
    icon: "📱",
    description: "Cutting-edge electronic components and consumer devices",
    productCount: 18,
  },
  {
    id: "garments",
    name: "Readymade Garments",
    icon: "👔",
    description: "High-quality fashion and textile garments",
    productCount: 24,
  },
  {
    id: "grocery",
    name: "Grocery",
    icon: "🛒",
    description: "Fresh and packaged grocery items for everyday needs and global export",
    productCount: 15,
  },
  {
    id: "pharma",
    name: "Pharmaceuticals",
    icon: "💊",
    description: "WHO-certified pharmaceutical products",
    productCount: 20,
  },
  {
    id: "chemicals",
    name: "Organic Chemicals",
    icon: "⚗️",
    description: "Industrial and laboratory-grade organic chemicals",
    productCount: 10,
  },
  {
    id: "petroleum",
    name: "Petroleum Products",
    icon: "🛢️",
    description: "Refined petroleum and petrochemical products",
    productCount: 8,
  },
  {
    id: "textiles",
    name: "Textile Products",
    icon: "🧵",
    description: "Raw and processed textile materials",
    productCount: 22,
  },
  {
    id: "mechanical",
    name: "Mechanical Equipment",
    icon: "⚙️",
    description: "Industrial machinery and mechanical components",
    productCount: 14,
  },
  {
    id: "jewellery",
    name: "Jewellery",
    icon: "💎",
    description: "Exquisite gold, silver, and gemstone jewellery",
    productCount: 16,
  },
];

export const products: Product[] = [
  {
    id: "1",
    name: "GKG Hing Energy Snacks",
    description:
      "A beloved Bikaner namkeen crafted by GKG — 100% natural dal-based snacks infused with the authentic flavor of hing (asafoetida). Crispy, light, and packed with traditional taste, these ISO 9001-2015 certified snacks are perfect for export to global Indian food markets. Made with no artificial flavors and sourced from the finest quality pulses.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk1.png",
    images: ["/gk1.png"],
    moq: 500,
    moqUnit: "kg",
    origin: "Bikaner, India",
    packaging: "Retail pouches (200g / 500g), Master carton",
    specifications: {
      Type: "Dal-based Namkeen",
      Flavor: "Hing (Asafoetida)",
      "Shelf Life": "6 months",
      Certification: "ISO 9001-2015, FSSAI",
      "100% Natural": "Yes",
    },
    featured: true,
    tagline: "Bikaner's Finest Namkeen",
  },
  {
    id: "2",
    name: "Premium Basmati Rice",
    description:
      "Extra-long grain aged Basmati rice sourced from the foothills of the Himalayas. Renowned for its distinctive aroma, fluffy texture, and non-sticky cooking quality — a prized export grain trusted by chefs and households across 50+ countries.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/g1.png",
    images: ["/g1.png"],
    moq: 500,
    moqUnit: "kg",
    origin: "Punjab & Haryana, India",
    packaging: "PP woven bags 25kg / 50kg, vacuum-sealed retail packs 1kg / 5kg",
    specifications: {
      "Grain Length": "\u22658.3mm (cooked)",
      "Aging Period": "\u226512 months",
      Moisture: "\u226412%",
      Aroma: "Natural (2-Acetyl-1-pyrroline)",
      Certification: "APEDA, FSSAI, ISO 9001:2015",
    },
    featured: true,
    tagline: "The Crown Jewel of Indian Grains",
  },
  {
    id: "3",
    name: "Cotton T-Shirts Collection",
    description:
      "Premium 100% combed cotton t-shirts available in various styles and colors. Manufactured with precision stitching and superior fabric quality.",
    category: "Readymade Garments",
    categoryId: "garments",
    imageUrl: "/cotton.png",
    images: ["/cotton.png", "/cotton1.png", "/cotton2.png"],
    moq: 1000,
    moqUnit: "pieces",
    origin: "India",
    packaging: "Individual polybag, master carton",
    specifications: {
      Fabric: "100% Combed Cotton",
      GSM: "160-180",
      Sizes: "S-3XL",
      Colors: "20+ options",
      Print: "Screen / DTG available",
    },
    featured: true,
    tagline: "Comfort Meets Quality",
  },
  {
    id: "4",
    name: "LED Panel Lights",
    description:
      "Energy-efficient LED panel lights suitable for commercial and residential use. High lumen output with minimal power consumption.",
    category: "Electronics",
    categoryId: "electronics",
    imageUrl: "/ledpannel.png",
    images: ["/ledpannel.png"],
    moq: 500,
    moqUnit: "units",
    origin: "India",
    packaging: "Foam insert, corrugated box",
    specifications: {
      Wattage: "18W / 24W / 36W",
      Lumens: "1800-3600 lm",
      "Color Temp": "3000K-6500K",
      Lifespan: "50,000 hours",
      Certification: "BIS, CE",
    },
    featured: true,
    tagline: "Illuminating the Future",
  },
  {
    id: "5",
    name: "Ghee (Clarified Butter)",
    description:
      "Traditional pure cow ghee made from fresh cream using the bilona method. Rich aroma and golden color, perfect for cooking and rituals.",
    category: "Dairy Products",
    categoryId: "dairy",
    imageUrl:
      "https://images.unsplash.com/photo-1631452180539-96aca7d48617?w=600&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1631452180539-96aca7d48617?w=800&h=600&fit=crop",
    ],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Tin containers 1L / 5L / 15L",
    specifications: {
      "Fat Content": "\u226599.5%",
      Moisture: "\u22640.5%",
      Method: "Traditional Bilona",
      "Shelf Life": "12 months",
      Certification: "FSSAI, Agmark",
    },
    featured: false,
    tagline: "Liquid Gold of India",
  },
  {
    id: "6",
    name: "Gold Necklace Set",
    description:
      "Intricately designed 22K gold necklace set featuring traditional Indian craftsmanship with modern aesthetics.",
    category: "Jewellery",
    categoryId: "jewellery",
    imageUrl: "/goldnecklace.png",
    images: ["/goldnecklace.png"],
    moq: 10,
    moqUnit: "sets",
    origin: "India",
    packaging: "Velvet box, tamper-proof seal",
    specifications: {
      Purity: "22K (916)",
      "Weight Range": "20-50g",
      Style: "Traditional & Contemporary",
      Hallmarking: "BIS Hallmarked",
      Certification: "BIS 916",
    },
    featured: true,
    tagline: "Art Meets Elegance",
  },
  {
    id: "7",
    name: "Paracetamol Tablets IP",
    description:
      "WHO-prequalified paracetamol tablets for fever and pain relief. Manufactured in GMP-certified facilities.",
    category: "Pharmaceuticals",
    categoryId: "pharma",
    imageUrl:
      "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&h=600&fit=crop",
    ],
    moq: 10000,
    moqUnit: "strips",
    origin: "India",
    packaging: "Blister pack, carton",
    specifications: {
      Strength: "500mg / 650mg",
      "Pack Size": "10 tablets/strip",
      Standards: "IP/BP/USP",
      "Shelf Life": "36 months",
      Certification: "WHO GMP, FDA",
    },
    featured: false,
    tagline: "Healthcare Without Borders",
  },
  {
    id: "8",
    name: "Silk Fabric Rolls",
    description:
      "Premium Mulberry silk fabric rolls in various weaves and colors, ideal for fashion designers and textile houses worldwide.",
    category: "Textile Products",
    categoryId: "textiles",
    imageUrl: "/silkrolls.png",
    images: ["/silkrolls.png"],
    moq: 100,
    moqUnit: "meters",
    origin: "India",
    packaging: "Roll packing, carton box",
    specifications: {
      Type: "Mulberry Silk",
      Width: "44-45 inches",
      Weight: "60-120 GSM",
      Weave: "Plain / Satin / Twill",
      Certification: "Silk Mark",
    },
    featured: true,
    tagline: "The Fabric of Royalty",
  },
  {
    id: "9",
    name: "CNC Machining Parts",
    description:
      "Precision CNC machined components in aluminum, steel, and brass. Custom manufacturing to specification with tight tolerances.",
    category: "Mechanical Equipment",
    categoryId: "mechanical",
    imageUrl:
      "https://images.unsplash.com/photo-1565043589221-1a6fd9ae45c7?w=600&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1565043589221-1a6fd9ae45c7?w=800&h=600&fit=crop",
    ],
    moq: 100,
    moqUnit: "pieces",
    origin: "India",
    packaging: "Anti-corrosion wrap, wooden crate",
    specifications: {
      Materials: "AL 6061, SS 304/316, Brass",
      Tolerance: "\u00b10.01mm",
      Finish: "Anodized / Polished / Powder Coat",
      "Lead Time": "15-20 days",
      Certification: "ISO 9001:2015",
    },
    featured: false,
    tagline: "Precision Engineered",
  },
  {
    id: "10",
    name: "Base Oil SN-150",
    description:
      "High-quality Group I base oil suitable for industrial lubricant manufacturing. Consistent viscosity index and low sulfur content.",
    category: "Petroleum Products",
    categoryId: "petroleum",
    imageUrl:
      "https://images.unsplash.com/photo-1518709766631-a6a7f45921c3?w=600&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1518709766631-a6a7f45921c3?w=800&h=600&fit=crop",
    ],
    moq: 20,
    moqUnit: "MT",
    origin: "India",
    packaging: "Flexi-bags / ISO Tanks",
    specifications: {
      Grade: "SN-150",
      Viscosity: "150 cSt @ 40\u00b0C",
      Sulfur: "\u22640.3%",
      "Flash Point": "\u2265200\u00b0C",
      Certification: "ISO 8217",
    },
    featured: false,
    tagline: "Industrial Grade Excellence",
  },
  {
    id: "11",
    name: "Citric Acid Monohydrate",
    description:
      "Food-grade citric acid monohydrate for use in beverages, food processing, and pharmaceutical applications.",
    category: "Organic Chemicals",
    categoryId: "chemicals",
    imageUrl:
      "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=600&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800&h=600&fit=crop",
    ],
    moq: 500,
    moqUnit: "kg",
    origin: "India",
    packaging: "HDPE bags, 25kg",
    specifications: {
      Purity: "\u226599.5%",
      Grade: "Food / Pharma",
      Moisture: "\u22648%",
      Form: "Crystalline Powder",
      Certification: "FSSAI, ISO",
    },
    featured: false,
    tagline: "Pure Chemistry, Pure Quality",
  },
  {
    id: "12",
    name: "Skimmed Milk Powder",
    description:
      "Premium spray-dried skimmed milk powder with excellent solubility. Ideal for dairy reconstitution and food manufacturing.",
    category: "Dairy Products",
    categoryId: "dairy",
    imageUrl:
      "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=600&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=800&h=600&fit=crop",
    ],
    moq: 1000,
    moqUnit: "kg",
    origin: "India",
    packaging: "Multi-wall kraft bags, 25kg",
    specifications: {
      Protein: "\u226534%",
      Fat: "\u22641.5%",
      Moisture: "\u22644%",
      Solubility: "\u226598%",
      Certification: "FSSAI, EIA",
    },
    featured: false,
    tagline: "Nutrition Beyond Borders",
  },
  {
    id: "13",
    name: "GKG Turmeric Powder",
    description: "Premium quality GKG-brand Turmeric Powder from Bikaner — vibrant golden colour, high curcumin content, and export-grade purity. FSSAI certified, packed for Indian grocery retail and global export.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk3.png",
    images: ["/gk3.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Spice of the Orient",
  },
  {
    id: "14",
    name: "GKG Coriander Powder",
    description: "GKG Coriander Powder from Bikaner — finely ground, export-quality, with a warm citrusy aroma. Purity with Taste is the brand promise. Ideal for retail and bulk export to global markets.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk4.png",
    images: ["/gk4.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Earthy & Aromatic",
  },
  {
    id: "15",
    name: "GKG Red Chilly Powder",
    description: "GKG Red Chilly Powder — bold colour, balanced heat, and export-grade quality from Bikaner. Purity with Taste certified. Packed in vibrant retail pouches for Indian grocery export markets worldwide.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk5.png",
    images: ["/gk5.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "The King of Spices",
  },
  {
    id: "16",
    name: "GKG American Tomato Khokha",
    description: "GKG American Tomato Khokha from Bikaner — a crispy, tangy snack loaded with bold tomato flavour. 100% vegetarian, no artificial colours, FSSAI certified. Perfect export snack for Indian diaspora markets.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk6.png",
    images: ["/gk6.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Queen of Spices",
  },
  {
    id: "17",
    name: "GKG Onion & Garlic Khokha",
    description: "GKG Onion & Garlic Khokha — a zesty Bikaner snack with a punchy onion-garlic flavour profile. Crispy, light, and addictive. Dil Khol Ke Khao or Khilao. FSSAI certified, export-ready packaging.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk7.png",
    images: ["/gk7.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Fiery & Bold",
  },
  {
    id: "18",
    name: "GKG Chatpata Khokha",
    description: "GKG Chatpata Khokha — the iconic Bikaner snack with a tangy, spicy chatpata flavour. Crispy bhuja-style snack loved across India and exported globally. Dil Khol Ke Khao or Khilao. FSSAI certified.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk8.png",
    images: ["/gk8.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Classic Indian Blend",
  },
  {
    id: "19",
    name: "GKG Bikaneri Bhujia",
    description: "Authentic GKG Bikaneri Bhujia — the original Bikaner namkeen made from moth bean (moth ki dal), seasoned with traditional spices. Crispy, light, and irresistibly flavourful. ISO certified, export-ready.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk9.png",
    images: ["/gk9.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Tiny Powerhouse",
  },
  {
    id: "20",
    name: "GKG Moong Dal Namkeen",
    description: "GKG Moong Dal Namkeen from Bikaner — crispy roasted moong dal snack seasoned with authentic spices. High protein, 100% natural, FSSAI certified. A popular Indian snack for retail and export markets.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk10.png",
    images: ["/gk10.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Ancient Healing Grain",
  },
  {
    id: "21",
    name: "GKG Nimbu Energy Snacks",
    description: "GKG Nimbu (Lemon) Energy Snacks from Bikaner — a tangy, refreshing snack with a burst of lemon flavour. 100% natural, no artificial colours, FSSAI certified. Crispy and light for any occasion.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk11.png",
    images: ["/gk11.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Nature's Antiseptic",
  },
  {
    id: "22",
    name: "GKG Nut Cracker",
    description: "GKG Nut Cracker from Bikaner — a crunchy, spiced roasted nut snack with bold flavours. Perfect as a tea-time treat or party snack. FSSAI certified, available in retail and bulk export packs.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk12.png",
    images: ["/gk12.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Mystical & Aromatic",
  },
  {
    id: "23",
    name: "GKG Premium Red Chilly Powder",
    description: "GKG Wellcome Premium Red Chilly Powder — extra-vibrant colour, bold heat, and authentic Bikaner quality. Multi-pack retail format, ideal for Indian grocery stores and export distribution worldwide.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk13.png",
    images: ["/gk13.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Sweet Warmth",
  },
  {
    id: "24",
    name: "GKG Premium Coriander",
    description: "GKG Premium Coriander Powder — a vibrant green-labelled export-quality variant with superior aroma and purity. Sourced and processed in Bikaner, certified for global food-grade export standards.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk14.png",
    images: ["/gk14.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Protein of India",
  },
  {
    id: "25",
    name: "GKG Premium Turmeric",
    description: "GKG Wellcome Premium Turmeric Powder — deep golden colour with high curcumin content. Multi-pack export format, perfect for Indian spice distribution internationally. FSSAI & export certified.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk15.png",
    images: ["/gk15.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Nature's Protein",
  },
  {
    id: "26",
    name: "GKG Chatpata Khokha Bhuja",
    description: "GKG Chatpata Khokha Bhuja — a small-pack Bikaner bhuja snack with an intense chatpata masala flavour. Crispy, fun, and packed with Indian street food taste. FSSAI certified, export-ready.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk16.png",
    images: ["/gk16.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Hearty & Wholesome",
  },
  {
    id: "27",
    name: "GKG Hing Khokha Bhuja",
    description: "GKG Hing Khokha Bhuja — a bhuja-style Bikaner snack with the signature hing (asafoetida) flavour. Crispy and light, ideal for export to Indian diaspora markets. FSSAI certified.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk17.png",
    images: ["/gk17.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Swift Nourishment",
  },
  {
    id: "28",
    name: "GKG Onion & Garlic Snacks Chura",
    description: "GKG Onion & Garlic Snacks Chura — a crunchy mixed bhuja chura with bold onion-garlic masala. Enjoyed as a namkeen snack across India and in export markets. FSSAI certified, 100% natural.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk18.png",
    images: ["/gk18.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "South Indian Staple",
  },
  {
    id: "29",
    name: "GKG Energy Snacks Bhuja",
    description: "GKG Energy Snacks Bhuja — a power-packed Bikaner bhuja in retail pouches. Made with premium dal-based ingredients and authentic Bikaner spices. FSSAI certified, ideal for Indian grocery export.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk19.png",
    images: ["/gk19.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Versatile Legume",
  },
  {
    id: "30",
    name: "GKG Energy Snacks Classic",
    description: "GKG Energy Snacks Classic Bhuja — the original Bikaner energy bhuja mix in retail packs. Made with 100% natural ingredients, no artificial colours. Perfect snack for export to global Indian food markets.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk20.png",
    images: ["/gk20.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Hearty & Filling",
  },
  {
    id: "31",
    name: "GKG Energy Snacks Green",
    description: "GKG Energy Snacks Green variant — a light, crispy bhuja snack in eye-catching green packaging. Made with select pulses and Bikaner spices. FSSAI certified, ideal for export and retail markets.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk21.png",
    images: ["/gk21.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Light & Fluffy",
  },
  {
    id: "32",
    name: "GKG Salted Popcorn",
    description: "GKG Salted Popcorn — light, fluffy popcorn with the perfect amount of salt. A popular ready-to-eat snack from Bikaner, available in retail and export packs. FSSAI certified, 100% vegetarian.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk22.png",
    images: ["/gk22.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Nutrient Rich",
  },
  {
    id: "33",
    name: "GKG Chatpata Popcorn",
    description: "GKG Chatpata Popcorn — tangy, spicy popcorn with a bold Indian masala twist. Ready-to-eat, FSSAI certified, 0% cholesterol. A hit snack for both domestic retail and global Indian grocery export.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk23.png",
    images: ["/gk23.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Wholesome Goodness",
  },
  {
    id: "34",
    name: "GKG Bengali Jhal Muri",
    description: "GKG Bengali Jhal Muri — the iconic Kolkata street snack made with puffed rice, spices, and tangy flavour. Ready-to-eat, FSSAI certified, 0% cholesterol. Perfect for Indian snack export worldwide.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk24.png",
    images: ["/gk24.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Daily Bread",
  },
  {
    id: "35",
    name: "GKG Bombay Bhel Puri",
    description: "GKG Bombay Bhel Puri — the famous Mumbai street snack of puffed rice, sev, and tangy chutneys in a ready-to-eat pack. FSSAI certified, 0% cholesterol. Ideal for Indian grocery retail and export.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk25.png",
    images: ["/gk25.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Versatile Grain",
  },
  {
    id: "36",
    name: "GKG Bengali Jhal Muri Mini",
    description: "GKG Bengali Jhal Muri Mini — bite-size retail pack of the classic Kolkata puffed rice snack. Tangy, spicy, and irresistible. FSSAI certified, 0% cholesterol. Great for Indian grocery export markets.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk26.png",
    images: ["/gk26.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Quick & Nutritious",
  },
  {
    id: "37",
    name: "GKG Bombay Bhel Puri Mini",
    description: "GKG Bombay Bhel Puri Mini — small retail packs of the signature Mumbai bhel puri snack. Ready-to-eat, FSSAI certified, 0% cholesterol. Loved by all age groups, perfect for export markets.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk27.png",
    images: ["/gk27.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Energy Booster",
  },
  {
    id: "38",
    name: "GKG Chatpati Bhelpuri",
    description: "GKG Chatpati Bhelpuri — a tangy, spicy bhelpuri snack with bold Indian street food flavours. Ready-to-eat, 0% cholesterol, FSSAI certified. Available in retail packs for domestic and export markets.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk28.png",
    images: ["/gk28.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Pure & Natural",
  },
  {
    id: "39",
    name: "GKG Chatpati Bhelpuri Classic",
    description: "GKG Chatpati Bhelpuri Classic — an alternative-pack variant of the beloved bhelpuri snack. Bold chatpata flavour, 0% cholesterol, FSSAI certified. Ready-to-eat, ideal for Indian snack export.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk29.png",
    images: ["/gk29.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Ancient Elixir",
  },
  {
    id: "40",
    name: "GKG Tikha Chatpata Falahari",
    description: "GKG Tikha Chatpata Falahari — a spicy-tangy fasting-friendly snack made with falahari ingredients. Enjoyed during religious fasts and as a gourmet snack. FSSAI certified, Bikaner crafted.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk30.png",
    images: ["/gk30.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Tropical Purity",
  },
  {
    id: "41",
    name: "GKG Kaju Badam Falahari",
    description: "GKG Kaju Badam Falahari — a premium fasting snack made with cashew (kaju) and almond (badam). A rich, guilt-free indulgence for vrat and falahari occasions. FSSAI certified, Bikaner crafted.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk31.png",
    images: ["/gk31.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Bold & Pungent",
  },
  {
    id: "42",
    name: "GKG Khatta Meetha Falahari",
    description: "GKG Khatta Meetha Falahari — a sweet-sour fasting-friendly snack from Bikaner. Made with falahari ingredients, perfect for vrat days or as a flavourful everyday snack. FSSAI certified.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk32.png",
    images: ["/gk32.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Morning Strength",
  },
  {
    id: "43",
    name: "GKG Bikaneri Bhujia Export",
    description: "GKG Bikaneri Bhujia in large export-format packs — the original Bikaner namkeen for global distribution. Made with moth ki dal and authentic Bikaner spices. ISO certified, FSSAI approved.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk33.png",
    images: ["/gk33.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Champagne of Teas",
  },
  {
    id: "44",
    name: "GKG Khatta Meetha",
    description: "GKG Khatta Meetha namkeen — a classic sweet-sour Indian snack mix in a premium export pack. Perfect blend of crunchy bits and bold flavours. FSSAI certified, ideal for Indian grocery export worldwide.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk34.png",
    images: ["/gk34.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Pure Antioxidant",
  },
  {
    id: "45",
    name: "GKG Nut Cracker Export",
    description: "GKG Nut Cracker in large export-format packs — a premium spiced roasted nut snack from Bikaner, available in Arabic & English labelling for Middle East and international export markets. FSSAI certified.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk35.png",
    images: ["/gk35.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Instant Indulgence",
  },
  {
    id: "46",
    name: "GKG Kucch Kaju Mixture",
    description: "GKG Kucch Kaju Mixture — an All-in-One crunchy namkeen mix with cashew pieces and a variety of fried snack elements. Rich, indulgent, and full of flavour. FSSAI certified, Bikaner crafted.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk36.png",
    images: ["/gk36.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Liquid Gold",
  },
  {
    id: "47",
    name: "GKG Kaju Badam Laccha",
    description: "GKG Kaju Badam Laccha — a premium namkeen featuring cashew and almond laccha (thin fried strips). A gourmet Indian snack from Bikaner for gifting and export. FSSAI certified.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk37.png",
    images: ["/gk37.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Ancient Sweetener",
  },
  {
    id: "48",
    name: "GKG Navratan Mixture",
    description: "GKG Navratan Mixture — a premium nine-ingredient namkeen mix with nuts, sev, and fried snack bits. Rich, festive, and perfect for gifting. FSSAI certified, available for retail and export.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk38.png",
    images: ["/gk38.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Desert Gold",
  },
  {
    id: "49",
    name: "GKG Khatta Meetha Chura",
    description: "GKG Khatta Meetha Chura — a popular sweet-sour namkeen chura from Bikaner, export packed. Bold flavour profile loved by Indian diaspora worldwide. FSSAI certified, 100% vegetarian.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk39.png",
    images: ["/gk39.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Sun-Kissed Sweetness",
  },
  {
    id: "50",
    name: "GKG Chatpata Matar",
    description: "GKG Chatpata Matar — crunchy roasted green peas with a bold chatpata masala coating. A high-protein snack from Bikaner loved across India. FSSAI certified, export-ready, 100% vegetarian.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk40.png",
    images: ["/gk40.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "White Gold",
  },
  {
    id: "51",
    name: "GKG Nut Cracker Arabic",
    description: "GKG Nut Cracker in Arabic-labelled export packs — specially packaged for Middle East distribution. Bold spiced roasted nut snack from Bikaner. FSSAI certified, Halal-friendly format.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk41.png",
    images: ["/gk41.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Brain Food",
  },
  {
    id: "52",
    name: "GKG Moong Dal Snack",
    description: "GKG Moong Dal Snack in large export packs — Arabic-labelled for Middle East markets. Premium roasted moong dal namkeen from Bikaner. FSSAI certified, high protein, 100% natural ingredients.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk42.png",
    images: ["/gk42.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Omega Rich",
  },
  {
    id: "53",
    name: "GKG Rasgulla Sweet",
    description: "GKG Rasgulla — the iconic soft and spongy Bengali sweet made from chhena (fresh paneer) soaked in light sugar syrup. Ready-to-eat, FSSAI certified. Popular Indian sweet for export and retail.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk43.png",
    images: ["/gk43.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Green Delight",
  },
  {
    id: "54",
    name: "GKG Chatpata Khokha Large",
    description: "GKG Chatpata Khokha in large export-format packs — the iconic Bikaner chatpata snack for bulk retail and international distribution. FSSAI certified, Dil Khol Ke Khao or Khilao.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk44.png",
    images: ["/gk44.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Tangy Tradition",
  },
  {
    id: "55",
    name: "GKG Himbu Energy Snacks",
    description: "GKG Himbu Energy Snacks — a lemon-lime variant energy snack from Bikaner in large export-format packs. Crispy, tangy, and made with 100% natural ingredients. FSSAI certified, export-ready.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk45.png",
    images: ["/gk45.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Spiced Medley",
  },
  {
    id: "56",
    name: "GKG Super Papad",
    description: "GKG Super Papad — crispy and tasty Bikaner-style papad, a classic Indian accompaniment. Made with traditional recipes, available in various flavours. FSSAI certified, ideal for retail and export.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk46.png",
    images: ["/gk46.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Sour & Tangy",
  },
  {
    id: "57",
    name: "GKG Tikha Chatpata Falahari Premium",
    description: "GKG Tikha Chatpata Falahari Premium — a bold, spicy-tangy falahari snack from Bikaner in large retail packs. Fasting-friendly, FSSAI certified, made with select falahari ingredients.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk47.png",
    images: ["/gk47.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Vitamin C Powerhouse",
  },
  {
    id: "58",
    name: "GKG HD Khoka",
    description: "GKG HD Khoka — a premium high-definition flavour khoka snack from Bikaner. Rich in taste, crispy in texture, and packed with bold masala notes. FSSAI certified, available for export markets.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk48.png",
    images: ["/gk48.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Warming Spice",
  },
  {
    id: "59",
    name: "GKG Shahi Hing Ratlami",
    description: "GKG Shahi Hing Ratlami — a royal-style Ratlami sev namkeen infused with hing (asafoetida) and traditional Ratlami spices. A premium snack from Bikaner crafted for connoisseurs. FSSAI certified.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk49.png",
    images: ["/gk49.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Tropical Tang",
  },
  {
    id: "60",
    name: "GKG Bikaneri Bhujia Classic",
    description: "GKG Bikaneri Bhujia Classic — the original Bikaner bhujia in traditional packaging. Made from moth ki dal with authentic Bikaner spices. ISO certified, FSSAI approved, ideal for global Indian grocery export.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk50.png",
    images: ["/gk50.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Digestive Wonder",
  },
  {
    id: "61",
    name: "Saffron (Kesar)",
    description: "Premium Kashmiri saffron threads with intense color and aroma.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk51.png",
    images: ["/gk51.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "The Red Gold",
  },
  {
    id: "62",
    name: "Dried Figs",
    description: "Naturally dried figs, sweet and chewy packed with fiber.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk52.png",
    images: ["/gk52.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Mediterranean Sweet",
  },
  {
    id: "63",
    name: "Poppy Seeds (Khus Khus)",
    description: "White poppy seeds used for texture in gravies and baked goods.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk53.png",
    images: ["/gk53.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Subtle Crunch",
  },
  {
    id: "64",
    name: "Flaxseeds (Alsi)",
    description: "Golden flaxseeds rich in omega-3 fatty acids and dietary fiber.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk54.png",
    images: ["/gk54.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Superfood Seeds",
  },
  {
    id: "65",
    name: "Chia Seeds",
    description: "Organic black chia seeds high in protein, fiber and omega-3.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk55.png",
    images: ["/gk55.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Tiny Superfoods",
  },
  {
    id: "66",
    name: "Sunflower Seeds",
    description: "Hulled sunflower seeds for snacking, baking and salad toppings.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk56.png",
    images: ["/gk56.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Sunny Nutrition",
  },
  {
    id: "67",
    name: "Pumpkin Seeds",
    description: "Organic green pumpkin seeds packed with zinc and magnesium.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk57.png",
    images: ["/gk57.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Mineral Rich",
  },
  {
    id: "68",
    name: "Besan (Gram Flour)",
    description: "Fine chickpea flour for pakoras, kadhi and Indian sweets.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk58.png",
    images: ["/gk58.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Versatile Flour",
  },
  {
    id: "69",
    name: "Rice Flour",
    description: "Finely milled rice flour for idiyappam, puttu and gluten-free baking.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk59.png",
    images: ["/gk59.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Gluten-Free Base",
  },
  {
    id: "70",
    name: "Corn Flour (Maize Starch)",
    description: "Fine corn starch used as a thickening agent in soups and sauces.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk60.png",
    images: ["/gk60.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Natural Thickener",
  },
  {
    id: "71",
    name: "Dry Coconut (Kopra)",
    description: "Dried whole coconut kernels used in chutneys and Indian sweets.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk61.png",
    images: ["/gk61.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Tropical Essence",
  },
  {
    id: "72",
    name: "Somnath Sabji Bhaji Freeze Dried",
    description: "Somnath Pav Bhaji brand Sabji Bhaji — Ready to Eat freeze-dried vegetable curry. Just add water and enjoy authentic Indian flavours in minutes. FSSAI certified, preservative-free, ideal for export and travel meals.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/p1.png",
    images: ["/p1.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "Bikaner, India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001, FSSAI", "Shelf Life": "6 months" },
    featured: false,
    tagline: "Bikaner's Finest",
  },
  {
    id: "73",
    name: "Somnath Green Bhaji Freeze Dried",
    description: "Somnath Pav Bhaji brand Green Bhaji — Ready to Eat freeze-dried green vegetable curry. Nutritious, flavourful, and quick to prepare. FSSAI certified, export-ready, perfect for Indian diaspora and travel meals.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/p2.png",
    images: ["/p2.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "Bikaner, India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001, FSSAI", "Shelf Life": "6 months" },
    featured: false,
    tagline: "Taste of Bikaner",
  },
  {
    id: "74",
    name: "Somnath Jain Pav Bhaji Freeze Dried",
    description: "Somnath Pav Bhaji brand Jain Pav Bhaji — Ready to Eat freeze-dried Jain-friendly pav bhaji without onion and garlic. Authentic taste, FSSAI certified, ideal for Jain travellers and global Indian food export.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/p3.png",
    images: ["/p3.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "Bikaner, India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001, FSSAI", "Shelf Life": "6 months" },
    featured: false,
    tagline: "Crispy & Delicious",
  },
  {
    id: "75",
    name: "Somnath Cheese Angoori Freeze Dried",
    description: "Somnath Pav Bhaji brand Cheese Angoori — Ready to Eat freeze-dried cheese-flavoured angoori (grape-sized) delight. A unique gourmet Indian treat, FSSAI certified, ready in minutes, ideal for global export.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/p4.png",
    images: ["/p4.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "Bikaner, India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001, FSSAI", "Shelf Life": "6 months" },
    featured: false,
    tagline: "Bold Indian Flavour",
  },
  {
    id: "76",
    name: "Somnath Green Pulao Freeze Dried",
    description: "Somnath Pav Bhaji brand Green Pulao — Ready to Eat freeze-dried fragrant green rice pulao. Restaurant-quality taste in minutes, FSSAI certified, no preservatives. Perfect for export and convenience meal markets.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/p5.png",
    images: ["/p5.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "Bikaner, India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001, FSSAI", "Shelf Life": "6 months" },
    featured: false,
    tagline: "Pure & Natural",
  },
  {
    id: "77",
    name: "Somnath Jain Pulao Freeze Dried",
    description: "Somnath Pav Bhaji brand Jain Pulao — Ready to Eat freeze-dried Jain-friendly rice pulao without onion and garlic. Wholesome, flavourful, and FSSAI certified. Ideal for Jain consumers and global Indian food export.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/p6.png",
    images: ["/p6.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "Bikaner, India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001, FSSAI", "Shelf Life": "6 months" },
    featured: false,
    tagline: "Street Food Favourite",
  },
  {
    id: "78",
    name: "Somnath Dudhi Halwa Freeze Dried",
    description: "Somnath Pav Bhaji brand Dudhi (Bottle Gourd) Halwa — Ready to Eat freeze-dried traditional Indian sweet. Rich, authentic, and ready in minutes. FSSAI certified, ideal for festive gifting and global dessert export.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/p7.png",
    images: ["/p7.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "Bikaner, India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001, FSSAI", "Shelf Life": "6 months" },
    featured: false,
    tagline: "Export Quality Snack",
  },
  {
    id: "79",
    name: "Somnath Gajar Halwa Freeze Dried",
    description: "Somnath Pav Bhaji brand Gajar (Carrot) Halwa — Ready to Eat freeze-dried classic Indian carrot dessert. Rich with the taste of slow-cooked carrots and milk, FSSAI certified, ready in minutes for global export.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/p8.png",
    images: ["/p8.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "Bikaner, India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001, FSSAI", "Shelf Life": "6 months" },
    featured: false,
    tagline: "Dil Khol Ke Khao",
  },
  {
    id: "80",
    name: "Somnath Dry Fruit Matho Freeze Dried",
    description: "Somnath Pav Bhaji brand Dry Fruit Matho — Ready to Eat freeze-dried dry fruit matho, a Rajasthani festive favourite. Packed with premium dry fruits, FSSAI certified, ideal for gifting and global Indian food export.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/p9.png",
    images: ["/p9.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "Bikaner, India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001, FSSAI", "Shelf Life": "6 months" },
    featured: false,
    tagline: "Authentic Bikaner Taste",
  },
  {
    id: "81",
    name: "Somnath Paneer Tikka Masala Freeze Dried",
    description: "Somnath Pav Bhaji brand Paneer Tikka Masala — Ready to Eat freeze-dried restaurant-style paneer in rich tikka masala gravy. FSSAI certified, preservative-free, just add water for an authentic Indian meal.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/p10.png",
    images: ["/p10.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "Bikaner, India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001, FSSAI", "Shelf Life": "6 months" },
    featured: false,
    tagline: "100% Vegetarian",
  },
  {
    id: "82",
    name: "Somnath Cheese Paneer Masala Freeze Dried",
    description: "Somnath Pav Bhaji brand Cheese Paneer Masala — Ready to Eat freeze-dried cheesy paneer masala curry. A rich, indulgent Indian meal ready in minutes. FSSAI certified, ideal for restaurant-quality export meals.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/p11.png",
    images: ["/p11.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "Bikaner, India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001, FSSAI", "Shelf Life": "6 months" },
    featured: false,
    tagline: "No Artificial Colours",
  },
  {
    id: "83",
    name: "Somnath Paneer Bhurji Freeze Dried",
    description: "Somnath Pav Bhaji brand Paneer Bhurji — Ready to Eat freeze-dried scrambled cottage cheese with spices. A popular Indian breakfast and meal, FSSAI certified, quick to prepare, ideal for global Indian food export.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/p12.png",
    images: ["/p12.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "Bikaner, India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001, FSSAI", "Shelf Life": "6 months" },
    featured: false,
    tagline: "Global Indian Snack",
  },
  {
    id: "84",
    name: "Somnath Mysore Gotala Freeze Dried",
    description: "Somnath Pav Bhaji brand Mysore Gotala — Ready to Eat freeze-dried South Indian Mysore-style savoury delight. Authentic regional flavours, FSSAI certified, ready in minutes. Ideal for South Indian cuisine export.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/p13.png",
    images: ["/p13.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "Bikaner, India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001, FSSAI", "Shelf Life": "6 months" },
    featured: false,
    tagline: "Purity With Taste",
  },
  {
    id: "85",
    name: "Somnath Kaju Kari Freeze Dried",
    description: "Somnath Pav Bhaji brand Kaju Kari — Ready to Eat freeze-dried rich cashew curry in a creamy gravy. A restaurant-style gourmet Indian dish, FSSAI certified, ready in minutes. Perfect for premium Indian food export.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/p14.png",
    images: ["/p14.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "Bikaner, India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001, FSSAI", "Shelf Life": "6 months" },
    featured: false,
    tagline: "Namkeen Excellence",
  },
  {
    id: "86",
    name: "Somnath Veg Toofani Freeze Dried",
    description: "Somnath Pav Bhaji brand Veg. Toofani — Ready to Eat freeze-dried spicy mixed vegetable curry with a 'toofani' (stormy) kick of flavour. FSSAI certified, preservative-free, ideal for spice lovers and global export.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/p15.png",
    images: ["/p15.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "Bikaner, India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001, FSSAI", "Shelf Life": "6 months" },
    featured: false,
    tagline: "Hari Bhai Brand",
  },
  {
    id: "87",
    name: "Somnath Veg Kolhapuri Masala Freeze Dried",
    description: "Somnath Pav Bhaji brand Veg. Kolhapuri Masala — Ready to Eat freeze-dried fiery Kolhapuri-style vegetable curry. Bold, spicy, and authentic, FSSAI certified. Ideal for lovers of robust Indian regional flavours worldwide.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/p16.png",
    images: ["/p16.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "Bikaner, India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001, FSSAI", "Shelf Life": "6 months" },
    featured: false,
    tagline: "Traditional Recipe",
  },
  {
    id: "88",
    name: "Somnath Jain Paneer Tikka Masala Freeze Dried",
    description: "Somnath Pav Bhaji brand Jain Paneer Tikka Masala — Ready to Eat freeze-dried Jain-friendly paneer tikka masala without onion and garlic. FSSAI certified, authentic restaurant flavour, ideal for Jain consumers globally.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/p17.png",
    images: ["/p17.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "Bikaner, India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001, FSSAI", "Shelf Life": "6 months" },
    featured: false,
    tagline: "Spicy & Crunchy",
  },
  {
    id: "89",
    name: "Somnath Jain Kaju Kari Freeze Dried",
    description: "Somnath Pav Bhaji brand Jain Kaju Kari — Ready to Eat freeze-dried Jain-friendly cashew curry without onion and garlic. Rich, creamy, and authentic, FSSAI certified. A premium Jain meal for global Indian food export.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/p18.png",
    images: ["/p18.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "Bikaner, India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001, FSSAI", "Shelf Life": "6 months" },
    featured: false,
    tagline: "Zero Cholesterol",
  },
  {
    id: "90",
    name: "Somnath Jeera Rice Dal Fry Freeze Dried",
    description: "Somnath Pav Bhaji brand Jeera Rice / Dal Fry — Ready to Eat freeze-dried classic Indian combo of cumin rice and spiced lentil fry. A complete wholesome meal, FSSAI certified, ideal for export and convenience meals.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/p19.png",
    images: ["/p19.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "Bikaner, India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001, FSSAI", "Shelf Life": "6 months" },
    featured: false,
    tagline: "Export Ready",
  },
  {
    id: "91",
    name: "Somnath Manchow Soup Freeze Dried",
    description: "Somnath Pav Bhaji brand Manchow Soup — Ready to Eat freeze-dried Indo-Chinese Manchow soup. Bold, spicy, and deeply satisfying, FSSAI certified, ready in minutes. A popular fusion meal for Indian food export markets.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/p20.png",
    images: ["/p20.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "Bikaner, India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001, FSSAI", "Shelf Life": "6 months" },
    featured: false,
    tagline: "Premium Quality",
  },
  {
    id: "92",
    name: "Somnath Bombay Bhel Freeze Dried",
    description: "Somnath Pav Bhaji brand Bombay Bhel — Ready to Eat freeze-dried Mumbai street-style bhel. Tangy, crunchy, and irresistible, FSSAI certified, ready in minutes. Perfect for Indian street food lovers worldwide.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/p21.png",
    images: ["/p21.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "Bikaner, India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001, FSSAI", "Shelf Life": "6 months" },
    featured: false,
    tagline: "Snack of India",
  },
  {
    id: "93",
    name: "Somnath Kadhi Khichdi Freeze Dried",
    description: "Somnath Pav Bhaji brand Kadhi Khichdi — Ready to Eat freeze-dried traditional Indian comfort food of spiced yogurt kadhi paired with soft khichdi. FSSAI certified, ready in minutes, ideal for global Indian food export.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/p22.png",
    images: ["/p22.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "Bikaner, India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001, FSSAI", "Shelf Life": "6 months" },
    featured: false,
    tagline: "Loved Worldwide",
  },
  {
    id: "94",
    name: "Somnath Locho Freeze Dried",
    description: "Somnath Pav Bhaji brand Locho — Ready to Eat freeze-dried Surat-famous Locho, a soft savoury steamed Gujarati snack. Authentic Surati street food flavour, FSSAI certified, ready in minutes for global Indian food export.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/p23.png",
    images: ["/p23.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "Bikaner, India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001, FSSAI", "Shelf Life": "6 months" },
    featured: false,
    tagline: "ISO Certified",
  },
];

export const founders: Founder[] = [
  {
    name: "Jayesh Avaiya",
    title: "Founder",
    phone: "+91 99253 53952",
    email: "[EMAIL_ADDRESS]",
    image: "/founders/jayesh.jpg",
  },
  {
    name: "Dipak Nakrani",
    title: "Founder",
    phone: "+91 97146 91751",
    email: "[EMAIL_ADDRESS]",
    image: "/founders/dipak.jpg",
  },
  {
    name: "Kalpesh Sabhani",
    title: "Founder",
    phone: "+91 99097 88944",
    email: "[EMAIL_ADDRESS]",
    image: "/founders/kalpesh.jpg",
  },
];

export const companyInfo = {
  name: "OM Export",
  tagline: "Global Trade & Export Services",
  email: "omexport291@gmail.com",
  description:
    "OM Export is a premier global trade and export company based in India, specializing in connecting international buyers with high-quality Indian products across diverse categories. With a commitment to excellence and reliability, we serve importers, distributors, and wholesalers in over 50 countries worldwide.",
  countriesServed: 50,
  totalProducts: 200,
  happyClients: 1000,
  yearsExperience: 10,
};
