import { Category, Product, Founder } from "./types";

export const categories: Category[] = [
  {
    id: "dairy",
    name: "Dairy Products",
    icon: "🧀",
    description:
      "Premium dairy exports including cheese, butter, and milk powder",
    productCount: 12,
  },
  {
    id: "electronics",
    name: "Electronics",
    icon: "📱",
    description: "Cutting-edge electronic components and consumer devices",
    productCount: 18,
  },
  {
    id: "garments",
    name: "Readymade Garments",
    icon: "👔",
    description: "High-quality fashion and textile garments",
    productCount: 24,
  },
  {
    id: "grocery",
    name: "Grocery",
    icon: "🛒",
    description: "Fresh and packaged grocery items for everyday needs and global export",
    productCount: 15,
  },
  {
    id: "pharma",
    name: "Pharmaceuticals",
    icon: "💊",
    description: "WHO-certified pharmaceutical products",
    productCount: 20,
  },
  {
    id: "chemicals",
    name: "Organic Chemicals",
    icon: "⚗️",
    description: "Industrial and laboratory-grade organic chemicals",
    productCount: 10,
  },
  {
    id: "petroleum",
    name: "Petroleum Products",
    icon: "🛢️",
    description: "Refined petroleum and petrochemical products",
    productCount: 8,
  },
  {
    id: "textiles",
    name: "Textile Products",
    icon: "🧵",
    description: "Raw and processed textile materials",
    productCount: 22,
  },
  {
    id: "mechanical",
    name: "Mechanical Equipment",
    icon: "⚙️",
    description: "Industrial machinery and mechanical components",
    productCount: 14,
  },
  {
    id: "jewellery",
    name: "Jewellery",
    icon: "💎",
    description: "Exquisite gold, silver, and gemstone jewellery",
    productCount: 16,
  },
];

export const products: Product[] = [
  {
    id: "1",
    name: "GKG Hing Energy Snacks",
    description:
      "A beloved Bikaner namkeen crafted by GKG — 100% natural dal-based snacks infused with the authentic flavor of hing (asafoetida). Crispy, light, and packed with traditional taste, these ISO 9001-2015 certified snacks are perfect for export to global Indian food markets. Made with no artificial flavors and sourced from the finest quality pulses.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk1.png",
    images: ["/gk1.png"],
    moq: 500,
    moqUnit: "kg",
    origin: "Bikaner, India",
    packaging: "Retail pouches (200g / 500g), Master carton",
    specifications: {
      Type: "Dal-based Namkeen",
      Flavor: "Hing (Asafoetida)",
      "Shelf Life": "6 months",
      Certification: "ISO 9001-2015, FSSAI",
      "100% Natural": "Yes",
    },
    featured: true,
    tagline: "Bikaner's Finest Namkeen",
  },
  {
    id: "2",
    name: "Organic Turmeric Powder",
    description:
      "High-curcumin organic turmeric powder, processed under strict quality controls. A cornerstone of Indian spice exports.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl:
      "https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=600&h=400&fit=crop",
    images: ["/gk2.png"],
    moq: 200,
    moqUnit: "kg",
    origin: "India",
    packaging: "Food-grade pouches, 1kg / 5kg / 25kg",
    specifications: {
      "Curcumin Content": "\u22653%",
      Moisture: "\u226410%",
      Type: "Alleppey/Erode",
      Certification: "USDA Organic, FSSAI",
    },
    featured: true,
    tagline: "Nature's Golden Healer",
  },
  {
    id: "3",
    name: "Cotton T-Shirts Collection",
    description:
      "Premium 100% combed cotton t-shirts available in various styles and colors. Manufactured with precision stitching and superior fabric quality.",
    category: "Readymade Garments",
    categoryId: "garments",
    imageUrl: "/cotton.png",
    images: ["/cotton.png", "/cotton1.png", "/cotton2.png"],
    moq: 1000,
    moqUnit: "pieces",
    origin: "India",
    packaging: "Individual polybag, master carton",
    specifications: {
      Fabric: "100% Combed Cotton",
      GSM: "160-180",
      Sizes: "S-3XL",
      Colors: "20+ options",
      Print: "Screen / DTG available",
    },
    featured: true,
    tagline: "Comfort Meets Quality",
  },
  {
    id: "4",
    name: "LED Panel Lights",
    description:
      "Energy-efficient LED panel lights suitable for commercial and residential use. High lumen output with minimal power consumption.",
    category: "Electronics",
    categoryId: "electronics",
    imageUrl: "/ledpannel.png",
    images: ["/ledpannel.png"],
    moq: 500,
    moqUnit: "units",
    origin: "India",
    packaging: "Foam insert, corrugated box",
    specifications: {
      Wattage: "18W / 24W / 36W",
      Lumens: "1800-3600 lm",
      "Color Temp": "3000K-6500K",
      Lifespan: "50,000 hours",
      Certification: "BIS, CE",
    },
    featured: true,
    tagline: "Illuminating the Future",
  },
  {
    id: "5",
    name: "Ghee (Clarified Butter)",
    description:
      "Traditional pure cow ghee made from fresh cream using the bilona method. Rich aroma and golden color, perfect for cooking and rituals.",
    category: "Dairy Products",
    categoryId: "dairy",
    imageUrl:
      "https://images.unsplash.com/photo-1631452180539-96aca7d48617?w=600&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1631452180539-96aca7d48617?w=800&h=600&fit=crop",
    ],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Tin containers 1L / 5L / 15L",
    specifications: {
      "Fat Content": "\u226599.5%",
      Moisture: "\u22640.5%",
      Method: "Traditional Bilona",
      "Shelf Life": "12 months",
      Certification: "FSSAI, Agmark",
    },
    featured: false,
    tagline: "Liquid Gold of India",
  },
  {
    id: "6",
    name: "Gold Necklace Set",
    description:
      "Intricately designed 22K gold necklace set featuring traditional Indian craftsmanship with modern aesthetics.",
    category: "Jewellery",
    categoryId: "jewellery",
    imageUrl: "/goldnecklace.png",
    images: ["/goldnecklace.png"],
    moq: 10,
    moqUnit: "sets",
    origin: "India",
    packaging: "Velvet box, tamper-proof seal",
    specifications: {
      Purity: "22K (916)",
      "Weight Range": "20-50g",
      Style: "Traditional & Contemporary",
      Hallmarking: "BIS Hallmarked",
      Certification: "BIS 916",
    },
    featured: true,
    tagline: "Art Meets Elegance",
  },
  {
    id: "7",
    name: "Paracetamol Tablets IP",
    description:
      "WHO-prequalified paracetamol tablets for fever and pain relief. Manufactured in GMP-certified facilities.",
    category: "Pharmaceuticals",
    categoryId: "pharma",
    imageUrl:
      "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&h=600&fit=crop",
    ],
    moq: 10000,
    moqUnit: "strips",
    origin: "India",
    packaging: "Blister pack, carton",
    specifications: {
      Strength: "500mg / 650mg",
      "Pack Size": "10 tablets/strip",
      Standards: "IP/BP/USP",
      "Shelf Life": "36 months",
      Certification: "WHO GMP, FDA",
    },
    featured: false,
    tagline: "Healthcare Without Borders",
  },
  {
    id: "8",
    name: "Silk Fabric Rolls",
    description:
      "Premium Mulberry silk fabric rolls in various weaves and colors, ideal for fashion designers and textile houses worldwide.",
    category: "Textile Products",
    categoryId: "textiles",
    imageUrl: "/silkrolls.png",
    images: ["/silkrolls.png"],
    moq: 100,
    moqUnit: "meters",
    origin: "India",
    packaging: "Roll packing, carton box",
    specifications: {
      Type: "Mulberry Silk",
      Width: "44-45 inches",
      Weight: "60-120 GSM",
      Weave: "Plain / Satin / Twill",
      Certification: "Silk Mark",
    },
    featured: true,
    tagline: "The Fabric of Royalty",
  },
  {
    id: "9",
    name: "CNC Machining Parts",
    description:
      "Precision CNC machined components in aluminum, steel, and brass. Custom manufacturing to specification with tight tolerances.",
    category: "Mechanical Equipment",
    categoryId: "mechanical",
    imageUrl:
      "https://images.unsplash.com/photo-1565043589221-1a6fd9ae45c7?w=600&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1565043589221-1a6fd9ae45c7?w=800&h=600&fit=crop",
    ],
    moq: 100,
    moqUnit: "pieces",
    origin: "India",
    packaging: "Anti-corrosion wrap, wooden crate",
    specifications: {
      Materials: "AL 6061, SS 304/316, Brass",
      Tolerance: "\u00b10.01mm",
      Finish: "Anodized / Polished / Powder Coat",
      "Lead Time": "15-20 days",
      Certification: "ISO 9001:2015",
    },
    featured: false,
    tagline: "Precision Engineered",
  },
  {
    id: "10",
    name: "Base Oil SN-150",
    description:
      "High-quality Group I base oil suitable for industrial lubricant manufacturing. Consistent viscosity index and low sulfur content.",
    category: "Petroleum Products",
    categoryId: "petroleum",
    imageUrl:
      "https://images.unsplash.com/photo-1518709766631-a6a7f45921c3?w=600&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1518709766631-a6a7f45921c3?w=800&h=600&fit=crop",
    ],
    moq: 20,
    moqUnit: "MT",
    origin: "India",
    packaging: "Flexi-bags / ISO Tanks",
    specifications: {
      Grade: "SN-150",
      Viscosity: "150 cSt @ 40\u00b0C",
      Sulfur: "\u22640.3%",
      "Flash Point": "\u2265200\u00b0C",
      Certification: "ISO 8217",
    },
    featured: false,
    tagline: "Industrial Grade Excellence",
  },
  {
    id: "11",
    name: "Citric Acid Monohydrate",
    description:
      "Food-grade citric acid monohydrate for use in beverages, food processing, and pharmaceutical applications.",
    category: "Organic Chemicals",
    categoryId: "chemicals",
    imageUrl:
      "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=600&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800&h=600&fit=crop",
    ],
    moq: 500,
    moqUnit: "kg",
    origin: "India",
    packaging: "HDPE bags, 25kg",
    specifications: {
      Purity: "\u226599.5%",
      Grade: "Food / Pharma",
      Moisture: "\u22648%",
      Form: "Crystalline Powder",
      Certification: "FSSAI, ISO",
    },
    featured: false,
    tagline: "Pure Chemistry, Pure Quality",
  },
  {
    id: "12",
    name: "Skimmed Milk Powder",
    description:
      "Premium spray-dried skimmed milk powder with excellent solubility. Ideal for dairy reconstitution and food manufacturing.",
    category: "Dairy Products",
    categoryId: "dairy",
    imageUrl:
      "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=600&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=800&h=600&fit=crop",
    ],
    moq: 1000,
    moqUnit: "kg",
    origin: "India",
    packaging: "Multi-wall kraft bags, 25kg",
    specifications: {
      Protein: "\u226534%",
      Fat: "\u22641.5%",
      Moisture: "\u22644%",
      Solubility: "\u226598%",
      Certification: "FSSAI, EIA",
    },
    featured: false,
    tagline: "Nutrition Beyond Borders",
  },
  {
    id: "13",
    name: "Cumin Seeds",
    description: "Aromatic cumin seeds with rich flavor, widely used in cooking worldwide.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk3.png",
    images: ["/gk3.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Spice of the Orient",
  },
  {
    id: "14",
    name: "Coriander Powder",
    description: "Finely ground coriander powder with a warm, citrusy aroma.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk4.png",
    images: ["/gk4.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Earthy & Aromatic",
  },
  {
    id: "15",
    name: "Black Pepper Whole",
    description: "Premium whole black pepper sourced from Kerala's finest farms.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk5.png",
    images: ["/gk5.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "The King of Spices",
  },
  {
    id: "16",
    name: "Green Cardamom",
    description: "Large bold green cardamom pods with intense flavor.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk6.png",
    images: ["/gk6.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Queen of Spices",
  },
  {
    id: "17",
    name: "Red Chilli Powder",
    description: "Bright red chilli powder with balanced heat and color.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk7.png",
    images: ["/gk7.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Fiery & Bold",
  },
  {
    id: "18",
    name: "Garam Masala Blend",
    description: "Traditional blend of aromatic whole spices, freshly ground.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk8.png",
    images: ["/gk8.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Classic Indian Blend",
  },
  {
    id: "19",
    name: "Mustard Seeds",
    description: "Small yellow and black mustard seeds ideal for pickling and cooking.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk9.png",
    images: ["/gk9.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Tiny Powerhouse",
  },
  {
    id: "20",
    name: "Fenugreek Seeds",
    description: "Golden fenugreek seeds known for their slightly bitter taste.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk10.png",
    images: ["/gk10.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Ancient Healing Grain",
  },
  {
    id: "21",
    name: "Cloves Whole",
    description: "Aromatic whole cloves packed with natural essential oils.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk11.png",
    images: ["/gk11.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Nature's Antiseptic",
  },
  {
    id: "22",
    name: "Star Anise",
    description: "Beautiful star-shaped spice with a strong licorice flavor.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk12.png",
    images: ["/gk12.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Mystical & Aromatic",
  },
  {
    id: "23",
    name: "Cinnamon Sticks",
    description: "Premium Ceylon cinnamon sticks with a sweet, warm aroma.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk13.png",
    images: ["/gk13.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Sweet Warmth",
  },
  {
    id: "24",
    name: "Toor Dal",
    description: "Split pigeon peas (toor dal), a staple protein-rich legume.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk14.png",
    images: ["/gk14.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Protein of India",
  },
  {
    id: "25",
    name: "Moong Dal",
    description: "Yellow split mung beans, easy to digest and highly nutritious.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk15.png",
    images: ["/gk15.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Nature's Protein",
  },
  {
    id: "26",
    name: "Chana Dal",
    description: "Split chickpea lentils with a nutty flavor, popular across South Asia.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk16.png",
    images: ["/gk16.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Hearty & Wholesome",
  },
  {
    id: "27",
    name: "Masoor Dal",
    description: "Red split lentils that cook quickly and taste earthy and mild.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk17.png",
    images: ["/gk17.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Swift Nourishment",
  },
  {
    id: "28",
    name: "Urad Dal",
    description: "Black gram lentils, essential for making dal makhani and idli.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk18.png",
    images: ["/gk18.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "South Indian Staple",
  },
  {
    id: "29",
    name: "Kabuli Chana",
    description: "Large white chickpeas used in curries, salads and hummus.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk19.png",
    images: ["/gk19.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Versatile Legume",
  },
  {
    id: "30",
    name: "Rajma (Kidney Beans)",
    description: "Dark red kidney beans with a rich, robust flavor.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk20.png",
    images: ["/gk20.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Hearty & Filling",
  },
  {
    id: "31",
    name: "Sona Masoori Rice",
    description: "Light and aromatic medium-grain rice from South India.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk21.png",
    images: ["/gk21.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Light & Fluffy",
  },
  {
    id: "32",
    name: "Parboiled Rice",
    description: "Pre-cooked and dried rice retaining more nutrients than white rice.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk22.png",
    images: ["/gk22.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Nutrient Rich",
  },
  {
    id: "33",
    name: "Brown Rice",
    description: "Whole grain rice with bran intact, rich in fiber and nutrients.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk23.png",
    images: ["/gk23.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Wholesome Goodness",
  },
  {
    id: "34",
    name: "Wheat Flour (Atta)",
    description: "Stone-ground whole wheat flour for rotis, chapatis and bread.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk24.png",
    images: ["/gk24.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Daily Bread",
  },
  {
    id: "35",
    name: "Semolina (Sooji)",
    description: "Coarse durum wheat semolina for upma, halwa and pasta.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk25.png",
    images: ["/gk25.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Versatile Grain",
  },
  {
    id: "36",
    name: "Poha (Flattened Rice)",
    description: "Flattened rice flakes for quick breakfast dishes and snacks.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk26.png",
    images: ["/gk26.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Quick & Nutritious",
  },
  {
    id: "37",
    name: "Sabudana (Tapioca)",
    description: "Tapioca pearls used for khichdi, kheer and fasting foods.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk27.png",
    images: ["/gk27.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Energy Booster",
  },
  {
    id: "38",
    name: "Groundnut Oil",
    description: "Cold-pressed groundnut (peanut) oil with a high smoke point.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk28.png",
    images: ["/gk28.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Pure & Natural",
  },
  {
    id: "39",
    name: "Sesame Oil",
    description: "Traditional cold-pressed sesame oil with a rich, nutty flavor.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk29.png",
    images: ["/gk29.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Ancient Elixir",
  },
  {
    id: "40",
    name: "Coconut Oil",
    description: "Virgin cold-pressed coconut oil from premium Kerala coconuts.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk30.png",
    images: ["/gk30.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Tropical Purity",
  },
  {
    id: "41",
    name: "Mustard Oil",
    description: "Pungent and flavorful cold-pressed mustard oil for cooking.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk31.png",
    images: ["/gk31.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Bold & Pungent",
  },
  {
    id: "42",
    name: "Assam Black Tea",
    description: "Bold and malty Assam black tea, ideal for strong morning brews.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk32.png",
    images: ["/gk32.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Morning Strength",
  },
  {
    id: "43",
    name: "Darjeeling Tea",
    description: "Delicate first-flush Darjeeling tea with a floral, muscatel flavor.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk33.png",
    images: ["/gk33.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Champagne of Teas",
  },
  {
    id: "44",
    name: "Green Tea",
    description: "Lightly processed green tea leaves packed with antioxidants.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk34.png",
    images: ["/gk34.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Pure Antioxidant",
  },
  {
    id: "45",
    name: "Instant Coffee Powder",
    description: "Rich and aromatic instant coffee powder from Coorg plantations.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk35.png",
    images: ["/gk35.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Instant Indulgence",
  },
  {
    id: "46",
    name: "Natural Honey",
    description: "Pure raw forest honey with natural enzymes and floral notes.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk36.png",
    images: ["/gk36.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Liquid Gold",
  },
  {
    id: "47",
    name: "Jaggery (Gur)",
    description: "Unrefined cane jaggery with rich minerals and a deep caramel taste.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk37.png",
    images: ["/gk37.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Ancient Sweetener",
  },
  {
    id: "48",
    name: "Dates (Khajoor)",
    description: "Soft and sweet Medjool and Safawi dates packed with energy.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk38.png",
    images: ["/gk38.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Desert Gold",
  },
  {
    id: "49",
    name: "Raisins (Kishmish)",
    description: "Sun-dried seedless grapes, plump and sweet for baking and snacking.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk39.png",
    images: ["/gk39.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Sun-Kissed Sweetness",
  },
  {
    id: "50",
    name: "Cashew Nuts",
    description: "Premium W180-W320 cashew kernels from Maharashtra and Goa.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk40.png",
    images: ["/gk40.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "White Gold",
  },
  {
    id: "51",
    name: "Almonds",
    description: "California-grade Indian almonds, crunchy and nutrient-rich.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk41.png",
    images: ["/gk41.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Brain Food",
  },
  {
    id: "52",
    name: "Walnuts",
    description: "Rich and buttery shelled walnuts high in omega-3 fatty acids.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk42.png",
    images: ["/gk42.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Omega Rich",
  },
  {
    id: "53",
    name: "Pistachios",
    description: "Premium green pistachios with a naturally rich and buttery taste.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk43.png",
    images: ["/gk43.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Green Delight",
  },
  {
    id: "54",
    name: "Mango Pickle (Achaar)",
    description: "Tangy and spicy raw mango pickle marinated in mustard oil.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk44.png",
    images: ["/gk44.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Tangy Tradition",
  },
  {
    id: "55",
    name: "Mixed Vegetable Pickle",
    description: "Assorted vegetables pickled in spiced oil and vinegar brine.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk45.png",
    images: ["/gk45.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Spiced Medley",
  },
  {
    id: "56",
    name: "Tamarind Paste",
    description: "Thick concentrated tamarind paste for chutneys, curries and sauces.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk46.png",
    images: ["/gk46.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Sour & Tangy",
  },
  {
    id: "57",
    name: "Amla (Indian Gooseberry)",
    description: "Dried amla powder and whole berries rich in Vitamin C.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk47.png",
    images: ["/gk47.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Vitamin C Powerhouse",
  },
  {
    id: "58",
    name: "Dry Ginger Powder",
    description: "Sun-dried ginger root ground into a fine powder with pungent aroma.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk48.png",
    images: ["/gk48.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Warming Spice",
  },
  {
    id: "59",
    name: "Dried Mango Powder (Amchur)",
    description: "Sour dried raw mango powder used as a souring agent in cooking.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk49.png",
    images: ["/gk49.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Tropical Tang",
  },
  {
    id: "60",
    name: "Asafoetida (Hing)",
    description: "Strong aromatic hing resin used sparingly for digestive cooking.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk50.png",
    images: ["/gk50.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Digestive Wonder",
  },
  {
    id: "61",
    name: "Saffron (Kesar)",
    description: "Premium Kashmiri saffron threads with intense color and aroma.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk51.png",
    images: ["/gk51.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "The Red Gold",
  },
  {
    id: "62",
    name: "Dried Figs",
    description: "Naturally dried figs, sweet and chewy packed with fiber.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk52.png",
    images: ["/gk52.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Mediterranean Sweet",
  },
  {
    id: "63",
    name: "Poppy Seeds (Khus Khus)",
    description: "White poppy seeds used for texture in gravies and baked goods.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk53.png",
    images: ["/gk53.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Subtle Crunch",
  },
  {
    id: "64",
    name: "Flaxseeds (Alsi)",
    description: "Golden flaxseeds rich in omega-3 fatty acids and dietary fiber.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk54.png",
    images: ["/gk54.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Superfood Seeds",
  },
  {
    id: "65",
    name: "Chia Seeds",
    description: "Organic black chia seeds high in protein, fiber and omega-3.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk55.png",
    images: ["/gk55.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Tiny Superfoods",
  },
  {
    id: "66",
    name: "Sunflower Seeds",
    description: "Hulled sunflower seeds for snacking, baking and salad toppings.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk56.png",
    images: ["/gk56.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Sunny Nutrition",
  },
  {
    id: "67",
    name: "Pumpkin Seeds",
    description: "Organic green pumpkin seeds packed with zinc and magnesium.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk57.png",
    images: ["/gk57.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Mineral Rich",
  },
  {
    id: "68",
    name: "Besan (Gram Flour)",
    description: "Fine chickpea flour for pakoras, kadhi and Indian sweets.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk58.png",
    images: ["/gk58.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Versatile Flour",
  },
  {
    id: "69",
    name: "Rice Flour",
    description: "Finely milled rice flour for idiyappam, puttu and gluten-free baking.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk59.png",
    images: ["/gk59.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Gluten-Free Base",
  },
  {
    id: "70",
    name: "Corn Flour (Maize Starch)",
    description: "Fine corn starch used as a thickening agent in soups and sauces.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk60.png",
    images: ["/gk60.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Natural Thickener",
  },
  {
    id: "71",
    name: "Dry Coconut (Kopra)",
    description: "Dried whole coconut kernels used in chutneys and Indian sweets.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk61.png",
    images: ["/gk61.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Tropical Essence",
  },
  {
    id: "72",
    name: "Kokum",
    description: "Dried kokum rinds used in Goan and Konkani cuisine for souring.",
    category: "Grocery",
    categoryId: "grocery",
    imageUrl: "/gk62.png",
    images: ["/gk62.png"],
    moq: 100,
    moqUnit: "kg",
    origin: "India",
    packaging: "Standard Export Packaging",
    specifications: { Quality: "Export Grade", Certification: "ISO 9001", "Shelf Life": "12 months" },
    featured: false,
    tagline: "Coastal Souring Agent",
  },
];

export const founders: Founder[] = [
  {
    name: "Jayesh Avaiya",
    title: "Founder",
    phone: "+91 99253 53952",
    email: "[EMAIL_ADDRESS]",
    image: "/founders/jayesh.jpg",
  },
  {
    name: "Dipak Nakrani",
    title: "Founder",
    phone: "+91 97146 91751",
    email: "[EMAIL_ADDRESS]",
    image: "/founders/dipak.jpg",
  },
  {
    name: "Kalpesh Sabhani",
    title: "Founder",
    phone: "+91 99097 88944",
    email: "[EMAIL_ADDRESS]",
    image: "/founders/kalpesh.jpg",
  },
];

export const companyInfo = {
  name: "OM Export",
  tagline: "Global Trade & Export Services",
  email: "omexport291@gmail.com",
  description:
    "OM Export is a premier global trade and export company based in India, specializing in connecting international buyers with high-quality Indian products across diverse categories. With a commitment to excellence and reliability, we serve importers, distributors, and wholesalers in over 50 countries worldwide.",
  countriesServed: 50,
  totalProducts: 200,
  happyClients: 1000,
  yearsExperience: 10,
};
